# Generated by Django 5.2.17 on 2026-10-04 08:25

import django.db.models.deletion
import recruitment.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=recruitment.models.upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('raw_text', models.TextField(blank=True)),
                ('source_blocks', models.JSONField(default=list)),
                ('candidate', models.JSONField(default=dict)),
                ('analysis', models.JSONField(default=dict)),
                ('analysis_revision', models.PositiveIntegerField(default=0)),
                ('analysis_date', models.DateField(null=True)),
                ('score', models.FloatField(null=True)),
                ('breakdown', models.JSONField(default=dict)),
                ('processing_status', models.CharField(default='queued', max_length=20)),
                ('decision_status', models.CharField(default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('input_fingerprint', models.CharField(blank=True, max_length=64)),
                ('processing_started_at', models.DateTimeField(null=True)),
                ('analyzed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('requirements_revision', models.PositiveIntegerField(default=1)),
                ('requirements_approved', models.BooleanField(default=False)),
                ('question_set', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.JSONField(default=dict)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('context_revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recruitment.application')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('fetch_status', models.CharField(default='pending', max_length=20)),
                ('snapshot', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('retry_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_analysis', to='recruitment.application')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('questions', models.JSONField(default=list)),
                ('question_source', models.CharField(blank=True, max_length=100)),
                ('answers', models.JSONField(default=dict)),
                ('answer_revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('deadline_at', models.DateTimeField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('evaluation', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='recruitment.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.job'),
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('canonical_key', models.CharField(max_length=150)),
                ('category', models.CharField(default='skills', max_length=30)),
                ('essential', models.BooleanField(default=False)),
                ('weight', models.PositiveSmallIntegerField(default=3)),
                ('minimum_months', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_count', models.PositiveIntegerField(blank=True, null=True)),
                ('jd_quote', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='recruitment.job')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'sha256'), name='unique_resume_per_job'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirement',
            constraint=models.UniqueConstraint(fields=('job', 'canonical_key'), name='unique_job_requirement'),
        ),
    ]
