# Generated by Django 5.2.17 on 2026-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extraction_meta',
            field=models.JSONField(default=dict),
        ),
    ]
