# Generated by Django 5.2.17 on 2026-10-04 12:09

import django.db.models.deletion
from django.db import migrations, models


def prepare_existing_shortlists(apps, schema_editor):
    Application = apps.get_model('recruitment', 'Application')
    Guide = apps.get_model('recruitment', 'InterviewGuide')
    for application in Application.objects.filter(decision_status='shortlisted').iterator():
        Guide.objects.get_or_create(application_id=application.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_job_extraction_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='question_set',
        ),
        migrations.CreateModel(
            name='InterviewGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_questions', models.JSONField(default=list)),
                ('edited_questions', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('context_fingerprint', models.CharField(blank=True, max_length=64)),
                ('edit_revision', models.PositiveIntegerField(default=0)),
                ('provenance', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('generation_token', models.UUIDField(editable=False, null=True)),
                ('processing_started_at', models.DateTimeField(null=True)),
                ('generated_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_guide', to='recruitment.application')),
            ],
        ),
        migrations.RunPython(prepare_existing_shortlists, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
